#version: '3'
#
#services:
#  server:
#    container_name: node_server
#    restart: always
#    build: .
#    volumes:
#      - ./:/node-app
#      - ./node_modules:/node-app/node_modules
#    environment:
#      NODE_ENV: development
#    #networks:
#    #  - webnet
#    depends_on:
#      - database
#    links:
#      - database
#    ports:
#      - '3000:3000'
#
#  mongo:
#    image: 'mongo'
#    container_name: mongo
#    ports:
#      - '27017:27017'
#    #networks:
#    #  - webnet
#    volumes:
#      - ./data/db:/data/db
#
#networks:
#  webnet:

version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'